version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: theory-training
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: theory-training
    ports:
      - "5432:5432"
    volumes:
      - theory_of_lang:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  theory_of_lang:
